apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: macys
  labels:
    component: mysql
    tier: db
    project: macys
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      component: mysql
      tier: db
      project: macys
  template:
    metadata:
      labels:
        component: mysql
        tier: db
        project: macys
    spec:
      containers:
      - name: mysql
        image: mysql:{{ .Values.deployment.image }}