apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: macys
  labels:
    purpose: helm-chart
    app: nginx
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      purpose: helm-chart
      app: nginx
  template:
    metadata:
      labels:
        purpose: helm-chart
        app: nginx
    spec:
      containers:
      - name: backend
        image: nginx:{{Values.deployment.imageversion}}                      
        