apiVersion: v1
kind: Service
metadata:
  name: Macys-service
  namespace: macys
spec:
  selector:
    purpose: helm
    app: nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: {{ .Values.service.port }}