apiVersion: v1
kind: PersistantVolume
metadata:
  name: ebs-static
spec: 
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-3jg43dhgvtf54547
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  VolumeName: ebs-static
  resources:
    requests:
      storage: 5Gi
---

apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: persistant-storage
  volumes:
    - name: app-data-volume
      persistentVolumeClaim:
        claimName: ebs-static