apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic
spec:
  accessModes:
    - ReadWriteMany # Allows multiple pods to connect simultaneously
  storageClassName: efs-dynamic
  resources:
    requests:
      storage: 5Gi