apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::324324234344:role/eksctl-macys-1-nodegroup-macys-NodeIn
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - macys-pod-reader
      userarn: arn:aws:iam::3824264667:user/shashi
      username: shashi
kind: ConfigMap
metadata:
  creationTimestamp: "default"
  name: aws-auth
  namespace: kube-system
  uid: eeenf324-5dfsf0r-87987yjhjgjg76  #don't delete this  


